### PR TITLE
enemies jump when player is above, and randomly

### PR DESCRIPTION
**Pull request by kusterlu**
The enemies jump up, when the player is in a range directly above them.
Aswell, they jump up every now and then with a certain probability, so they do not all collect at the bottom line.
--> If we could exclude the Logfiles from Git, that would be great.
--> This still has to get right tests. I 'set asleep' some, to be able to upload it here.

### CODE REVIEW

**Comment by Cas-B** [comment]
The logfiles are already ignored, I changed the .gitignore file a few days ago.

**Comment by Cas-B** [comment]
It seems the enemies not only jump when above them, is this right?

**Comment by Cas-B** [comment]
PMD reports useless parantheses in the Enemy class after your edits, please fix this.

**Comment by kusterlu** [comment]
@Cas-B The enemies jump aswell randomly now and then. This is an extra feature. <feature,

**Comment by kusterlu** [comment]
I fixed everything which was discussed in the reviews. <layout,

**Comment by Cas-B** [comment]
Only the outcommented Tests problem is left.

**Comment by kusterlu** [comment]
@Cas-B the tests fail because of smth. of the test-syntax which I don't know. Logically they should work.
So I do not delete them, that the test-writer for this part does not have to write everything anew. <layout,

**Comment by Cas-B** [comment]
The test writer was me, I deleted them as there will be a few things differently, it will give a nice merge conflict with the design pattern as it changes the whole movement for the enemy structure.


@rjbergTU @RobJBerg This branch can be reviewed.

**Pull request merged**
