### PR TITLE
Redesigned Entity Movement according Strategy Pattern & Fixed bug wit…

### PR DESCRIPTION
**Pull request by Cas-B**
…h colliding with enbubbled enemy < feature, bug, performance

### CODE REVIEW

**Comment by rjbergTU** [comment]
I would have left out the I in IMoveBehaviour

**Comment by rjbergTU** [comment]
Also, I would have put a getSpeed method in the move behaviour, and redirect Entity.getSpeed() to that method.

**Comment by Cas-B** [comment]
The I is an identifier for interfaces to recognize it easier.

**Comment by Cas-B** [comment]
The move behaviour is only for how to walk it is not about what the speed exactly is, only how it is changed according to the different kind of movements. The speed is still part of the entity itself and so the getSpeed should remain in that class.

**Pull request merged**
